export const TOKEN_TITLE = {
  ATTRIBUTE: "Attribut",
  BRACKET: "Accolade",
  COLUMN: "Colonne",
  COMMA: "Virgule",
  CONDITION: "Condition",
  CONTAINER: "Conteneur",
  EXPRESSION: "Expression",
  FIELD: "Champ",
  HEADER: "En-tête",
  HEADER_WITH_LIST: "En-tête avec liste",
  HOOK: "Crochet",
  JUMPLINE: "Saut de ligne",
  LIST: "Liste",
  NUMBER: "Nombre",
  OPERATOR: "Opérateur",
  PARENTHESE: "Parenthèse",
  PROPERTY: "Propriété",
  QUOTE: "Guillemet",
  SEPARATOR: "Séparateur",
  SPACE: "Espace",
  TAG: "Balise",
  TEXT: "Texte",
  TOKEN: "Jeton",
  VARIABLE_GET: "variable_get",
  VARIABLE_INIT: "variable_init",
  VARIABLE_SET: "variable_set",
} as const;
