export const TOKEN_TYPE = {
  ATTRIBUTE: "attribute",
  BRACKET: "bracket",
  COLUMN: "column",
  COMMA: "comma",
  CONDITION: "condition",
  EXPRESSION: "expression",
  FIELD: "field",
  HEADER: "header",
  HEADER_WITH_LIST: "header_with_list",
  HOOK: "hook",
  JUMPLINE: "jumpLine",
  LIST: "list",
  NUMBER: "number",
  OPERATOR: "operator",
  PARENTHESE: "parenthese",
  PROPERTY: "property",
  QUOTE: "quote",
  SEPARATOR: "separator",
  SPACE: "space",
  TAG: "tag",
  TEXT: "text",
  VARIABLE_GET: "variable_get",
  VARIABLE_INIT: "variable_init",
  VARIABLE_SET: "variable_set",
} as const;
